### ISSUE TITLE
how to identify the promoter bin interacting with multiple enhancer bins

### ISSUE THREAD

**Issue by zcq23** [LuJiansen/scNanoHi-C#6]
Hi jiansen,
I'm very curious about the promoter bin interacting with multiple enhancer bins identifying, the enhancer-promoter pairs were predicted by ABC model calculated by bulk data and downloaded through the offered file, but how to use that to identify which pairs fell into the bin? 

By looking for these pairs locations in each cell or the merge cells, and whether is there any contact site? because the E-P pairs were not identifed using the single cell and also not using the scNanoHi-C data.

Looking forward to your reply very much and manyyyyyyyyyyyyyyyyyyyyyyyy thanks!!!

**Comment by LuJiansen** [comment]
Hi zcq,
Thank you for interested to our work. 

Due to the sparsity of single-cell data, we identify the multiway E-P interactions based on all the concatemers of merged cells. Since only E-P pairs captured by the same concatemers were counted, there were contacts among them, although the resolution may be 10 or 20 kb. 

The detailed methods have been described in the Method section of our paper and the code is available in [multiple_regulatory_structures.R](https://github.com/LuJiansen/scNanoHi-C/blob/master/analysis/multiple_interaction/multiple_regulatory_structures.R). 

Feel free to ask if you have any other questions.

**Comment by zcq23** [comment]
ohhhhhhhhhhhhhhh I see!!! so thankful for your reply and suggestion I know your point!! manyyyyyyyyyyyyyyyyyyyyyyyy thanks again and wish everything goes well with your work and life!!!!!!!✌✌✌
